/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GameDAO;
import controller.PointDAO;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Games;
import model.Users;

/**
 *
 * @author qtrngcrusoe
 */
public class MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm
     */
    Users user;
    Games game;
    GameDAO gd = new GameDAO();

    public MainFrm(Games g, Users us) {
        initComponents();
        game = g;
        user = us;
        SapXep(game);
        btn = 0;
        btnReset.setEnabled(false);
        btnStart.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlbCount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbHour = new javax.swing.JLabel();
        lbMinute = new javax.swing.JLabel();
        lbSecond = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jigsaw Puzzle - Play");
        setBackground(new java.awt.Color(0, 51, 51));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/logoNho.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 88)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JIGSAW PUZZLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlbCount.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jlbCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCount.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clicked");

        lbHour.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbHour.setText("00 :");

        lbMinute.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbMinute.setText("00 :");

        lbSecond.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbSecond.setText("00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Time");

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lbHour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMinute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSecond)
                .addGap(37, 37, 37))
            .addComponent(jlbCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHour)
                    .addComponent(lbMinute)
                    .addComponent(lbSecond))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbCount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        btnStart.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int counter; //Biến đếm số lần click
    static int btn = 0;

    String[] mangHinh = new String[15];
    int[] mangSo = new int[15];
    int[] mangSoHopLe = new int[15];
    int n = 0;
    int soHopLe = 0;

    static int seconds = 1;
    static int minutes = 0;
    static int hours = 0;

    Thread t;

    public void Doi() { //Hàm trộn các ô game
        counter = 0;
        jlbCount.setText("0");

        mangHinh[0] = game.getImg1();
        mangHinh[1] = game.getImg2();
        mangHinh[2] = game.getImg3();
        mangHinh[3] = game.getImg4();
        mangHinh[4] = game.getImg5();
        mangHinh[5] = game.getImg6();
        mangHinh[6] = game.getImg7();
        mangHinh[7] = game.getImg8();
        mangHinh[8] = game.getImg9();
        mangHinh[9] = game.getImg10();
        mangHinh[10] = game.getImg11();
        mangHinh[11] = game.getImg12();
        mangHinh[12] = game.getImg13();
        mangHinh[13] = game.getImg14();
        mangHinh[14] = game.getImg15();

        for (int i = 0; i <= 14; i++) {
            mangSo[i] = i;
        }
        soHopLe = 0;

        for (int i = 0; i < mangHinh.length; i++) {
            int index = (int) (Math.random() * 15);
            String temp = mangHinh[i];
            mangHinh[i] = mangHinh[index];
            mangHinh[index] = temp;

            int tempSo = mangSo[i];
            mangSo[i] = mangSo[index];
            mangSo[index] = tempSo;
        }
        for (int i = 0; i <= 14; i++) {
            n = mangSo[i] - 1;
            for (int j = i - 1; j >= 0; j--) {
                for (int k = 0; k <= j; k++) {
                    if (mangSo[j] == n || mangSo[k] == n) {
                        n--;
                        if (n < 0) {
                            n = 0;
                        }
                    }
                }
            }
            mangSoHopLe[i] = n;
        }
        for (int i = 0; i <= 14; i++) {
            soHopLe += mangSoHopLe[i];
        }

        //System.out.println(soHopLe+1);
        System.out.println("Mang so dau tien khi random");
        for (int i = 0; i <= 14; i++) {
            System.out.print(mangSo[i] + ", ");

        }
        System.out.println("");
        System.out.println("Mang so sau khi nghich dao hoan vi");
        for (int i = 0; i <= 14; i++) {
            System.out.print(mangSoHopLe[i] + ", ");
        }
        System.out.println("");
        System.out.println(soHopLe+1);

        jButton1.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[0])));
        jButton2.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[1])));
        jButton3.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[2])));
        jButton4.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[3])));
        jButton5.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[4])));
        jButton6.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[5])));
        jButton7.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[6])));
        jButton8.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[7])));
        jButton9.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[8])));
        jButton10.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[9])));
        jButton11.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[10])));
        jButton12.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[11])));
        jButton13.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[12])));
        jButton14.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[13])));
        jButton15.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + mangHinh[14])));
        jButton20.setIcon(null);

        if (((soHopLe + 1) % 2) != 0) {
            Doi();
        }
    }

    void Xep(JButton btn1, JButton btn2) { //Hàm di chuyển ô
        if (btn2.getIcon() == null) {
            btn2.setIcon(btn1.getIcon());
            btn1.setIcon(null);
            counter = counter + 1;
            jlbCount.setText(Integer.toString(counter));
        }
    }

    public void kiemTra() { //Kiem tra
        try {
            String b1 = ((ImageIcon) jButton1.getIcon()).getDescription();
            String b2 = ((ImageIcon) jButton2.getIcon()).getDescription();
            String b3 = ((ImageIcon) jButton3.getIcon()).getDescription();
            String b4 = ((ImageIcon) jButton4.getIcon()).getDescription();
            String b5 = ((ImageIcon) jButton5.getIcon()).getDescription();
            String b6 = ((ImageIcon) jButton6.getIcon()).getDescription();
            String b7 = ((ImageIcon) jButton7.getIcon()).getDescription();
            String b8 = ((ImageIcon) jButton8.getIcon()).getDescription();
            String b9 = ((ImageIcon) jButton9.getIcon()).getDescription();
            String b10 = ((ImageIcon) jButton10.getIcon()).getDescription();
            String b11 = ((ImageIcon) jButton11.getIcon()).getDescription();
            String b12 = ((ImageIcon) jButton12.getIcon()).getDescription();
            String b13 = ((ImageIcon) jButton13.getIcon()).getDescription();
            String b14 = ((ImageIcon) jButton14.getIcon()).getDescription();
            String b15 = ((ImageIcon) jButton15.getIcon()).getDescription();

            if (gd.kiemTra(b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, game) == true) { //Kiem tra
                btn = 0;
                t.stop();
                String time = lbHour.getText() + " " + lbMinute.getText() + " " + lbSecond.getText();
                PointDAO pd = new PointDAO();

                pd.addPoint(user.getUsername(), game.getGameID(), time, counter); //Add diem vo CSDL
                JOptionPane.showMessageDialog(this, "You won the Game with time: " + time + " and clicked: " + counter, "Congratulations", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {

        }
    }

    public void SapXep(Games g) {
        GameDAO gd = new GameDAO();
        gd.sapXep(g);
        jButton1.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg1())));
        jButton2.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg2())));
        jButton3.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg3())));
        jButton4.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg4())));
        jButton5.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg5())));
        jButton6.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg6())));
        jButton7.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg7())));
        jButton8.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg8())));
        jButton9.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg9())));
        jButton10.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg10())));
        jButton11.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg11())));
        jButton12.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg12())));
        jButton13.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg13())));
        jButton14.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg14())));
        jButton15.setIcon(new ImageIcon(getClass().getClassLoader().getResource("resources/" + g.getImg15())));
        jButton20.setIcon(null);

    }
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (btn == 1) {
            Xep(jButton12, jButton8);
            Xep(jButton12, jButton11);
            Xep(jButton12, jButton20);
            kiemTra();
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (btn == 1) {
            Xep(jButton1, jButton2);
            Xep(jButton1, jButton5);
            kiemTra();
        }
        System.out.println(soHopLe);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (btn == 1) {
            Xep(jButton2, jButton1);
            Xep(jButton2, jButton3);
            Xep(jButton2, jButton6);
            kiemTra();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (btn == 1) {
            Xep(jButton3, jButton2);
            Xep(jButton3, jButton4);
            Xep(jButton3, jButton7);
            kiemTra();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (btn == 1) {
            Xep(jButton4, jButton3);
            Xep(jButton4, jButton8);
            kiemTra();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (btn == 1) {
            Xep(jButton5, jButton1);
            Xep(jButton5, jButton6);
            Xep(jButton5, jButton9);
            kiemTra();
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (btn == 1) {
            Xep(jButton6, jButton7);
            Xep(jButton6, jButton2);
            Xep(jButton6, jButton5);
            Xep(jButton6, jButton10);
            kiemTra();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (btn == 1) {
            Xep(jButton7, jButton3);
            Xep(jButton7, jButton6);
            Xep(jButton7, jButton8);
            Xep(jButton7, jButton11);
            kiemTra();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (btn == 1) {
            Xep(jButton8, jButton4);
            Xep(jButton8, jButton7);
            Xep(jButton8, jButton12);
            kiemTra();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (btn == 1) {
            Xep(jButton9, jButton5);
            Xep(jButton9, jButton10);
            Xep(jButton9, jButton13);
            kiemTra();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (btn == 1) {
            Xep(jButton10, jButton9);
            Xep(jButton10, jButton11);
            Xep(jButton10, jButton6);
            Xep(jButton10, jButton14);
            kiemTra();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (btn == 1) {
            Xep(jButton11, jButton7);
            Xep(jButton11, jButton10);
            Xep(jButton11, jButton12);
            Xep(jButton11, jButton15);
            kiemTra();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (btn == 1) {
            Xep(jButton13, jButton9);
            Xep(jButton13, jButton14);
            kiemTra();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (btn == 1) {
            Xep(jButton14, jButton10);
            Xep(jButton14, jButton13);
            Xep(jButton14, jButton15);
            kiemTra();
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (btn == 1) {
            Xep(jButton15, jButton14);
            Xep(jButton15, jButton11);
            Xep(jButton15, jButton20);
            kiemTra();
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        if (btn == 1) {
            Xep(jButton20, jButton12);
            Xep(jButton20, jButton15);
            kiemTra();
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        btn = 0;

        counter = 0;
        jlbCount.setText("0");

        lbSecond.setText("00");
        lbMinute.setText("00 :");
        lbHour.setText("00 :");

        SapXep(game);

        seconds = 0;
        minutes = 0;
        hours = 0;

        btnReset.setEnabled(false);
        btnStart.setEnabled(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Doi();
        btnReset.setEnabled(true);
        btnStart.setEnabled(false);
        btn = 1;
        t = new Thread() {
            @Override
            public void run() {
                for (;;) {
                    if (btn == 1) {
                        try {
                            sleep(1000);

                            if (seconds > 60) {
                                seconds = 0;
                                minutes++;
                            }
                            if (minutes > 60) {
                                seconds = 0;
                                minutes = 0;
                                hours++;
                            }

                            if (seconds == 60) {
                                lbSecond.setText("00");
                            } else if (seconds > 9) {
                                lbSecond.setText("" + seconds);
                            } else {
                                lbSecond.setText("0" + seconds);
                            }

                            seconds++;

                            if (minutes == 60) {
                                lbMinute.setText("00 :");
                            }
                            if (minutes > 9) {
                                lbMinute.setText(minutes + " :");
                            } else {
                                lbMinute.setText("0" + minutes + " :");
                            }

                            if (hours > 9) {
                                lbHour.setText(hours + " :");
                            } else {
                                lbHour.setText("0" + hours + " :");
                            }
                        } catch (Exception ex) {
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (btn == 0) {
            dispose();
            new TrangChu(user).setVisible(true);
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "If you exit now, your score will not be saved", "Warning", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                dispose();
                new TrangChu(user).setVisible(true);
            } else {

            }
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jlbCount;
    private javax.swing.JLabel lbHour;
    private javax.swing.JLabel lbMinute;
    private javax.swing.JLabel lbSecond;
    // End of variables declaration//GEN-END:variables
}
